{
  "formatVersion": "1.1",
  "component": {
    "group": "dapanda.api.core",
    "module": "dapanda-api-core",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jackson"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.9.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-0.0.22.jar",
          "url": "dapanda-api-core-0.0.22.jar",
          "size": 580870,
          "sha512": "41aed6fbbfbdc3a8b6471bbd9a003d52f4087c3ddea6ffa4095ca13e04eb2070b2fe840cded425aeeb178fea389d3310d52026b6fa41952eb915230574cbe09f",
          "sha256": "1d7cc3aac51e0a8ad65cddd6a01a79d859be66eb16cffa6470ab6f89da53a2e9",
          "sha1": "1abd8a1fbb10265d239254de11ff80bc171c928f",
          "md5": "fc2318694f0e2f1338cc4be3bac8b3cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-http-server-netty"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-http-client"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-runtime"
        },
        {
          "group": "io.micronaut.kotlin",
          "module": "micronaut-kotlin-runtime"
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-validation"
        },
        {
          "group": "io.micronaut.beanvalidation",
          "module": "micronaut-hibernate-validator"
        },
        {
          "group": "io.micronaut.sql",
          "module": "micronaut-jdbc-hikari"
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-core"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-caffeine"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-noop"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-slf4j",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "8.0.33"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jackson"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.9.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-0.0.22.jar",
          "url": "dapanda-api-core-0.0.22.jar",
          "size": 580870,
          "sha512": "41aed6fbbfbdc3a8b6471bbd9a003d52f4087c3ddea6ffa4095ca13e04eb2070b2fe840cded425aeeb178fea389d3310d52026b6fa41952eb915230574cbe09f",
          "sha256": "1d7cc3aac51e0a8ad65cddd6a01a79d859be66eb16cffa6470ab6f89da53a2e9",
          "sha1": "1abd8a1fbb10265d239254de11ff80bc171c928f",
          "md5": "fc2318694f0e2f1338cc4be3bac8b3cd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-0.0.22-sources.jar",
          "url": "dapanda-api-core-0.0.22-sources.jar",
          "size": 191344,
          "sha512": "106bea628b24c793631d023363e41742dd846ceb37b393404a7fd31489fd4957750b4e1183f79174cdea19a9ccbf9146e1622aa3179de8b1070af903c92df274",
          "sha256": "61d066088b83a22b9463c8f9f9f63748e4782fced56206b1afac8b005cf4adc3",
          "sha1": "852622bff0283ee70cbf09cd0fb3976cc39bf2bb",
          "md5": "51c2a48ee41799b73a2d3b8560027a41"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-0.0.22-javadoc.jar",
          "url": "dapanda-api-core-0.0.22-javadoc.jar",
          "size": 255968,
          "sha512": "b01289fc5b57736aa4c0fdfdcfd6f19f52a18e3655250da6ed6b2b8521468bc6273e59d817a8187d4203b8c75ce0b7e306cbaa3b4da1d0e21316354f1074ff56",
          "sha256": "238629c358d84da8c0ce9a30b7cd022d2cbd35a44c8033cf95168c9750703d1c",
          "sha1": "555fc543c13406fa16f4ccedaff1b041e0250367",
          "md5": "a6dde8350e1bc9f4b2eaec7a13d44532"
        }
      ]
    }
  ]
}
