{
  "formatVersion": "1.1",
  "component": {
    "group": "dapanda.api.core",
    "module": "dapanda-api-core",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-0.0.9.jar",
          "url": "dapanda-api-core-0.0.9.jar",
          "size": 408871,
          "sha512": "2b892bbe19aac5fbf72abd5daa0da6bafe672eb4bbd803a91d96fe3a593cfe69dd1b89df015e1fa9607cafb8833b948df70dd9dc142a209ca04aeb724502d5f6",
          "sha256": "e6e14ee5d34eb8257f5f7382219805fa359a0316ee63acb11b040967cabc3459",
          "sha1": "c4004f53d46576d9cb0ba19582cc99f7bf66014a",
          "md5": "500485cbae8fbbc945c2956ff8c5b652"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-http-server-netty"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-http-client"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-runtime"
        },
        {
          "group": "io.micronaut.kotlin",
          "module": "micronaut-kotlin-runtime"
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-validation"
        },
        {
          "group": "io.micronaut.beanvalidation",
          "module": "micronaut-hibernate-validator"
        },
        {
          "group": "io.micronaut.sql",
          "module": "micronaut-jdbc-hikari"
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-core"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-caffeine"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-noop"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-slf4j",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "8.0.29"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-0.0.9.jar",
          "url": "dapanda-api-core-0.0.9.jar",
          "size": 408871,
          "sha512": "2b892bbe19aac5fbf72abd5daa0da6bafe672eb4bbd803a91d96fe3a593cfe69dd1b89df015e1fa9607cafb8833b948df70dd9dc142a209ca04aeb724502d5f6",
          "sha256": "e6e14ee5d34eb8257f5f7382219805fa359a0316ee63acb11b040967cabc3459",
          "sha1": "c4004f53d46576d9cb0ba19582cc99f7bf66014a",
          "md5": "500485cbae8fbbc945c2956ff8c5b652"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-0.0.9-sources.jar",
          "url": "dapanda-api-core-0.0.9-sources.jar",
          "size": 170420,
          "sha512": "4b2693fdc3b52e03451b45b01a93ba4bfecceccec08b9888cc1c945b3def7ffe70ec3aa5c32db8da17db3f2ffea3867963d1bb49a665ba73c868345efbc1000e",
          "sha256": "ac5e2bdedbada16497159b798ac3b5ff3b3fb205099f246cbc9ef206aee24092",
          "sha1": "38a306d82edc4b059039274e702954919a762ed6",
          "md5": "045ec01f0b2a58afa13478cc6be2d70d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-0.0.9-javadoc.jar",
          "url": "dapanda-api-core-0.0.9-javadoc.jar",
          "size": 573187,
          "sha512": "b82289d70ed5dde53469122d0b34b5681c544b24f4a5f57c006e955c40a627999776762d5a368cf8a5c373042fa3d5de8fc2a0f1d0413f3b442a6776ce1457ff",
          "sha256": "457369df0fcc703efe3f0be1961d433424a1077350617d4d0894ffddfac33526",
          "sha1": "5ff6dde0717f3adb8cd865967f0bf51358ff060e",
          "md5": "f098f7d0df42fd46813d310edca840da"
        }
      ]
    }
  ]
}
