{
  "formatVersion": "1.1",
  "component": {
    "group": "dapanda.api.core",
    "module": "dapanda-api-core",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.9.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-0.0.10.jar",
          "url": "dapanda-api-core-0.0.10.jar",
          "size": 452521,
          "sha512": "298641adebfc20d630cd4641b9a6117dc001b8024c57260106bc07e95e5e7967858450d23efd9bc6b682a6eb899788bda99d1f7a52531bf6da693a27e735e595",
          "sha256": "797aee3d59e11293e9944f8ef86340d7722cb7e581b65ab12065b710360a23db",
          "sha1": "99edc4c7a472d27e6b1273a3b895adf02ef9f10d",
          "md5": "8740c55c14aa0d41a786b4d4ccb77292"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-http-server-netty"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-http-client"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-runtime"
        },
        {
          "group": "io.micronaut.kotlin",
          "module": "micronaut-kotlin-runtime"
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-validation"
        },
        {
          "group": "io.micronaut.beanvalidation",
          "module": "micronaut-hibernate-validator"
        },
        {
          "group": "io.micronaut.sql",
          "module": "micronaut-jdbc-hikari"
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-core"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-caffeine"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-noop"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-slf4j",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "8.0.33"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.9.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-0.0.10.jar",
          "url": "dapanda-api-core-0.0.10.jar",
          "size": 452521,
          "sha512": "298641adebfc20d630cd4641b9a6117dc001b8024c57260106bc07e95e5e7967858450d23efd9bc6b682a6eb899788bda99d1f7a52531bf6da693a27e735e595",
          "sha256": "797aee3d59e11293e9944f8ef86340d7722cb7e581b65ab12065b710360a23db",
          "sha1": "99edc4c7a472d27e6b1273a3b895adf02ef9f10d",
          "md5": "8740c55c14aa0d41a786b4d4ccb77292"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-0.0.10-sources.jar",
          "url": "dapanda-api-core-0.0.10-sources.jar",
          "size": 178747,
          "sha512": "80a6ef9804918f3926e7f53feed07e396e06833bf0e89f5af7b49915435cff869eff89d0c515213e6c8eed50a2dfc3c1cb19a764eb900f187bd22df71028a496",
          "sha256": "9b67ec459e1263bfd06f490d8db1702c87c819a754de6a234dec689837084796",
          "sha1": "774352969a3ee7d7a994204a55f456be6be21101",
          "md5": "849993bbb35b5250ed2f2d3399f7f018"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-0.0.10-javadoc.jar",
          "url": "dapanda-api-core-0.0.10-javadoc.jar",
          "size": 255884,
          "sha512": "2b5959c87c28b670c628418731f474581a5b870c960fc22bd293a8e14f89292998e91eb9f3c17ff2a065e8e32041b33ccf8aa01c3dee468e822308c69fdaec83",
          "sha256": "09f5b4ea978eae2db1fb97eb378ec15c0fddad2f947ea13fcf6b13d807ad2bb4",
          "sha1": "6f9dc544a55191c94da16eae78a09f9b9481b645",
          "md5": "e562bcdc982a16d26bf9f0340336d501"
        }
      ]
    }
  ]
}
