{
  "formatVersion": "1.1",
  "component": {
    "group": "dapanda.api.core",
    "module": "dapanda-api-core",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-0.0.6.jar",
          "url": "dapanda-api-core-0.0.6.jar",
          "size": 403680,
          "sha512": "3ecee84d1102c8eb32c144e6651315ca9c659779d2bbbc445abf81ca0c473471032f9aec9379e8d59613c579a92441a388eb9e3dbae785ab8ec7b08b6053e615",
          "sha256": "242a8002f29a926cdbc882134801831035b7329e2c40a69aedbe6141d3b0f55c",
          "sha1": "4d791b435c0c7c3934bf838782750b7272eb334d",
          "md5": "e0fbd85ddc02ee269a54f2ad5a001550"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-http-server-netty"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-http-client"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-runtime"
        },
        {
          "group": "io.micronaut.kotlin",
          "module": "micronaut-kotlin-runtime"
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-validation"
        },
        {
          "group": "io.micronaut.beanvalidation",
          "module": "micronaut-hibernate-validator"
        },
        {
          "group": "io.micronaut.sql",
          "module": "micronaut-jdbc-hikari"
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-core"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-caffeine"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-noop"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "8.0.29"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.ajoberstar.git-publish",
          "module": "gradle-git-publish",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-0.0.6.jar",
          "url": "dapanda-api-core-0.0.6.jar",
          "size": 403680,
          "sha512": "3ecee84d1102c8eb32c144e6651315ca9c659779d2bbbc445abf81ca0c473471032f9aec9379e8d59613c579a92441a388eb9e3dbae785ab8ec7b08b6053e615",
          "sha256": "242a8002f29a926cdbc882134801831035b7329e2c40a69aedbe6141d3b0f55c",
          "sha1": "4d791b435c0c7c3934bf838782750b7272eb334d",
          "md5": "e0fbd85ddc02ee269a54f2ad5a001550"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-0.0.6-all.jar",
          "url": "dapanda-api-core-0.0.6-all.jar",
          "size": 44108821,
          "sha512": "0ae6eccc823efaf406e981b7a688954331357d7e25f8724690795a094ac67fabbc4c3d03fe8d57db53729e7a58e90d3f1bec1d53c0c193cff18b6a32165e74dd",
          "sha256": "474095467c31fb6aa61f3f31de6f988bd81740a70e17f651040d1d0837a8ac92",
          "sha1": "98dc050fc893d963c357bdc299f8a4cd596277d7",
          "md5": "bbb93a29e74c60fc93d56fca44a52cf5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-0.0.6-sources.jar",
          "url": "dapanda-api-core-0.0.6-sources.jar",
          "size": 165249,
          "sha512": "f4dfba8a9801a4fd782445e0c7bf668bbaa15c529e1ba75f621837002cf9c526e75f5faea86179f76e46688cc9e0b4f1ecacda1969e8edc309855f5524e40546",
          "sha256": "9fe36cc94d8971c629baca71e781b10ceb1c09093e713806064b33cf95e856af",
          "sha1": "a9f80190728729bfcbb80eb647360f725fd4dd0c",
          "md5": "5b766429a19cd4bb73dbeed7122e4e9b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-0.0.6-javadoc.jar",
          "url": "dapanda-api-core-0.0.6-javadoc.jar",
          "size": 570018,
          "sha512": "6c4f5dcf3f68ea2a5591e09da0caa3acc79e82603844ce265b4b64bfd357b3090bcfd1d570fd03a5f59886dc75704259d2dc0d5c8d8f0b5a84f1fafa1abe8b95",
          "sha256": "95486f8b70a7e9fc4413ada7790c1a9b7ccc1a18aad5f7be993e9ca8789de26c",
          "sha1": "fbdab4c3e81bde28bdec406d75f415ca0901ebfe",
          "md5": "513612d071be129484d6c4a39dc9f1ee"
        }
      ]
    }
  ]
}
