{
  "formatVersion": "1.1",
  "component": {
    "group": "dapanda.api.core",
    "module": "dapanda-api-core",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-jackson-databind"
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jackson"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut.platform",
          "module": "micronaut-platform",
          "version": {
            "requires": "4.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-1.0.1.jar",
          "url": "dapanda-api-core-1.0.1.jar",
          "size": 616424,
          "sha512": "c33ad5f6c4c9e4b61f8f36b5106432617f036e618add0ba67c982aeed702650419ebc4865d3d2e92c23d1a8802626ff3c4f3309b1c9adc5fe1ed3eb79d0846cc",
          "sha256": "a64c78838a8c56b3a2bd2488a197621b5c5f10207b1c3f851979d23153cf1f93",
          "sha1": "56890baf9fb53ab3007f2211a873046f590a2a18",
          "md5": "cc7974f7df1c306f1265f7e9129f90c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-http-server-netty"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-http-client"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-runtime"
        },
        {
          "group": "io.micronaut.kotlin",
          "module": "micronaut-kotlin-runtime"
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api"
        },
        {
          "group": "io.micronaut.validation",
          "module": "micronaut-validation"
        },
        {
          "group": "jakarta.el",
          "module": "jakarta.el-api",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "io.micronaut.beanvalidation",
          "module": "micronaut-hibernate-validator",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "org.glassfish",
          "module": "jakarta.el",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "io.micronaut.sql",
          "module": "micronaut-jdbc-hikari"
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-core"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-caffeine"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-noop"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-slf4j",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "8.0.33"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-jackson-databind"
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jackson"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut.platform",
          "module": "micronaut-platform",
          "version": {
            "requires": "4.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-1.0.1.jar",
          "url": "dapanda-api-core-1.0.1.jar",
          "size": 616424,
          "sha512": "c33ad5f6c4c9e4b61f8f36b5106432617f036e618add0ba67c982aeed702650419ebc4865d3d2e92c23d1a8802626ff3c4f3309b1c9adc5fe1ed3eb79d0846cc",
          "sha256": "a64c78838a8c56b3a2bd2488a197621b5c5f10207b1c3f851979d23153cf1f93",
          "sha1": "56890baf9fb53ab3007f2211a873046f590a2a18",
          "md5": "cc7974f7df1c306f1265f7e9129f90c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-1.0.1-sources.jar",
          "url": "dapanda-api-core-1.0.1-sources.jar",
          "size": 207119,
          "sha512": "2557e221256822d668d70552b4671a3e64c46c679ce171081399f9f25ddfe558dbe41d9c4167ac12a851e1a6092034a22a6f43273ec6dc0a88f7043c5860c219",
          "sha256": "c54b0db61a57492cdc61ccf77e1f1686dd84a29ddfbd67b1dc6a8d0b5d5927d6",
          "sha1": "a359b0ae88536e4cbffa926344ab9c2e5dd9f909",
          "md5": "5dc325355cf7691897c8790f28ae38b9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-1.0.1-javadoc.jar",
          "url": "dapanda-api-core-1.0.1-javadoc.jar",
          "size": 272031,
          "sha512": "e38d6e4afa36571155d05d9ae7ca73e83a3ec5dff0d7468ee8441a2ca9beb06be6f8384c5354891625f9092483559455f1268c424c78b94271f4d2e412a3cd0e",
          "sha256": "92db3ba82d30fe9834e48a1f3c39493f95272595c5121f8a88279499d84d0a28",
          "sha1": "263ad7bbc970436ecf819823d802cb84a91bd730",
          "md5": "b3784862dc52556ef3aa69e07a03b995"
        }
      ]
    }
  ]
}
