{
  "formatVersion": "1.1",
  "component": {
    "group": "dapanda.api.core",
    "module": "dapanda-api-core",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-jackson-databind"
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jackson"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut.platform",
          "module": "micronaut-platform",
          "version": {
            "requires": "4.4.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-1.0.5.jar",
          "url": "dapanda-api-core-1.0.5.jar",
          "size": 614989,
          "sha512": "16bd00f40f916968177b26fd1375d8a7d82ff3de38d3d29555c10e2c6138449aef7d409e35da09221272465fe406505924d90f47f64ec468313d44961e7e30ad",
          "sha256": "5b4f8230c09d118611e5e85dc737c2be96abc847510be64542ce4020caa729a0",
          "sha1": "d4be04e4f82131b16248a5bff40aa82980564d1d",
          "md5": "24fa5c56467eae730ec4208b09f71817"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-http-server-netty"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-http-client"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-runtime"
        },
        {
          "group": "io.micronaut.kotlin",
          "module": "micronaut-kotlin-runtime"
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api"
        },
        {
          "group": "io.micronaut.validation",
          "module": "micronaut-validation"
        },
        {
          "group": "jakarta.el",
          "module": "jakarta.el-api",
          "version": {
            "requires": "6.0.1"
          }
        },
        {
          "group": "io.micronaut.sql",
          "module": "micronaut-jdbc-hikari"
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-core"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-caffeine"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-noop"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-slf4j",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j",
          "version": {
            "requires": "8.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-jackson-databind"
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jackson"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut.platform",
          "module": "micronaut-platform",
          "version": {
            "requires": "4.4.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-1.0.5.jar",
          "url": "dapanda-api-core-1.0.5.jar",
          "size": 614989,
          "sha512": "16bd00f40f916968177b26fd1375d8a7d82ff3de38d3d29555c10e2c6138449aef7d409e35da09221272465fe406505924d90f47f64ec468313d44961e7e30ad",
          "sha256": "5b4f8230c09d118611e5e85dc737c2be96abc847510be64542ce4020caa729a0",
          "sha1": "d4be04e4f82131b16248a5bff40aa82980564d1d",
          "md5": "24fa5c56467eae730ec4208b09f71817"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-1.0.5-sources.jar",
          "url": "dapanda-api-core-1.0.5-sources.jar",
          "size": 206292,
          "sha512": "c0e1d5a5745deeff6e267a264abe3258a369559e99b85f92ea035e5c9d1c5f90890f9501b85ed566f7ecb12957acfc0ec49427b5b5410cd5d83c2ebf51499564",
          "sha256": "fab93837e1afac78317a9fa907f849f73b68e000adb2c2e2315f951bf764c510",
          "sha1": "fffba97bc0236a7740e177c14d4dc349b4ba1016",
          "md5": "1da42f9ac0c2964e51606d8e8e87316d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-1.0.5-javadoc.jar",
          "url": "dapanda-api-core-1.0.5-javadoc.jar",
          "size": 271489,
          "sha512": "2826a4d475e10671903b1a3776e2287f3012f24bb9d19c37a6c7b9013069fd53356090c00100571cdd0ade6bafaa1e7013b54eaa22f39f2837dbfe0198d48a38",
          "sha256": "ebcfe8eee760c35f8ea5561c90934aec07d49fd04ebd0920bcef04bad99418ec",
          "sha1": "4e031f301f51fd09c584556c30ee208ede309cdf",
          "md5": "718555407c47e0a19bc18e3f052c363f"
        }
      ]
    }
  ]
}
