{
  "formatVersion": "1.1",
  "component": {
    "group": "dapanda.api.core",
    "module": "dapanda-api-core",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-unspecified.jar",
          "url": "dapanda-api-core-unspecified.jar",
          "size": 403680,
          "sha512": "afc00b2fc8e62a85b6d6a2d66e1a9d03fd95e58ad8728bd55ba2ac1ad04a3525f95b60e6c9769206d5ef61e6ac4597fa7286bf8b27d2d190bbf3164ab0ae6984",
          "sha256": "d555be1f1a9a1d3eb7a292024c6ab7316feb5839877471a066d183de2a256734",
          "sha1": "8f87cb7ef554dc275fd880b77bc19a31be7a405b",
          "md5": "7f44efa633b309ca65d89a174bc5b475"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-http-server-netty"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-http-client"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-runtime"
        },
        {
          "group": "io.micronaut.kotlin",
          "module": "micronaut-kotlin-runtime"
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-validation"
        },
        {
          "group": "io.micronaut.beanvalidation",
          "module": "micronaut-hibernate-validator"
        },
        {
          "group": "io.micronaut.sql",
          "module": "micronaut-jdbc-hikari"
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-core"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-caffeine"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-noop"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "8.0.29"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-unspecified.jar",
          "url": "dapanda-api-core-unspecified.jar",
          "size": 403680,
          "sha512": "afc00b2fc8e62a85b6d6a2d66e1a9d03fd95e58ad8728bd55ba2ac1ad04a3525f95b60e6c9769206d5ef61e6ac4597fa7286bf8b27d2d190bbf3164ab0ae6984",
          "sha256": "d555be1f1a9a1d3eb7a292024c6ab7316feb5839877471a066d183de2a256734",
          "sha1": "8f87cb7ef554dc275fd880b77bc19a31be7a405b",
          "md5": "7f44efa633b309ca65d89a174bc5b475"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-unspecified-all.jar",
          "url": "dapanda-api-core-unspecified-all.jar",
          "size": 32909696,
          "sha512": "a7ac35e52b4a49565fa2efce1f444e07d7fa1f0dc4e1260b1ff1337938d7c11cf4aed1b339b2f15190435f1451a61ecb79b09b0f12e8fc4913c6c3d0ee89c172",
          "sha256": "33e5175bf05508c5842462c1ff8595bcf5b84a4e74ab3cf4d5a1977344627df3",
          "sha1": "3c5874d43d59d41794c0f5266a422343e15d673c",
          "md5": "f75a8ba729c45de2d424be2758eb8321"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-unspecified-sources.jar",
          "url": "dapanda-api-core-unspecified-sources.jar",
          "size": 165249,
          "sha512": "b10098245cdba35f4304a3394a80acb4512d8b852732d432baa9c42520370556c123c62b35f61f68af18f1e0b1cc685c1e2b88a0ab58823ae9f49208a1812401",
          "sha256": "c75f2a446cc00f009627ba9e2633192cd14f6d4d408e85791500d7749e39ad03",
          "sha1": "ccc29dea43951b7af9c73012dd0bff74521aa5a2",
          "md5": "af9383d86c442cab383f9d992abd0d74"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-unspecified-javadoc.jar",
          "url": "dapanda-api-core-unspecified-javadoc.jar",
          "size": 569680,
          "sha512": "c06e1ab01fd8ce3d72428e4203c152f993b858caa61089c684ec1bf8b6bc42bd3134b2db1c5d290828e7e4a457bb929ccdbdb6fa7ce4f45c90a6494a370417d9",
          "sha256": "7f7a64fdd2e32218549c7a4fad1577067dfd7dfe9b8fe24a38eb78c0f2c84abf",
          "sha1": "8d41b19cec9516b7b7e9ae435d63411934849f2e",
          "md5": "6a49989baa6b03f7bb349b5b9c140fe1"
        }
      ]
    }
  ]
}
