{
  "formatVersion": "1.1",
  "component": {
    "group": "dapanda.api.core",
    "module": "dapanda-api-core",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.9.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-0.0.14.jar",
          "url": "dapanda-api-core-0.0.14.jar",
          "size": 482704,
          "sha512": "d0199bf0dd9eb1b5c66b185b318844fe9458ed87138636a022a3d1cb45507b8278cd548b144ca57d7e7b708c52656ba26a81b4ceb229a09bf84c7877cefcac43",
          "sha256": "56dba48794dc9b9f3a4630643a84785faf695ad11f020ef49883a3ff5f124453",
          "sha1": "d8bbc03379457b536756a4e981df5a31624e93db",
          "md5": "834ddb694b11b3919e446e7d74daeb9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-http-server-netty"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-http-client"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-runtime"
        },
        {
          "group": "io.micronaut.kotlin",
          "module": "micronaut-kotlin-runtime"
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-validation"
        },
        {
          "group": "io.micronaut.beanvalidation",
          "module": "micronaut-hibernate-validator"
        },
        {
          "group": "io.micronaut.sql",
          "module": "micronaut-jdbc-hikari"
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-core"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-caffeine"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-noop"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-slf4j",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "8.0.33"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.9.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-0.0.14.jar",
          "url": "dapanda-api-core-0.0.14.jar",
          "size": 482704,
          "sha512": "d0199bf0dd9eb1b5c66b185b318844fe9458ed87138636a022a3d1cb45507b8278cd548b144ca57d7e7b708c52656ba26a81b4ceb229a09bf84c7877cefcac43",
          "sha256": "56dba48794dc9b9f3a4630643a84785faf695ad11f020ef49883a3ff5f124453",
          "sha1": "d8bbc03379457b536756a4e981df5a31624e93db",
          "md5": "834ddb694b11b3919e446e7d74daeb9c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-0.0.14-sources.jar",
          "url": "dapanda-api-core-0.0.14-sources.jar",
          "size": 182235,
          "sha512": "2627add386bc06b55b574c6e22e8c0194648b0271aee998701f5f126b22e054f47763add99bf64578bebd61d22d3f671c1352f21101fba5eb06014d00771bd70",
          "sha256": "abc96f775ba537b3b9f0ed728c5a34870a37c7299b5bed980db9c99b6bc5869a",
          "sha1": "04ac64ef9f7e0ed3f8ab0ca54005134a9c0f01ef",
          "md5": "0d98c4947c15ed93b4925543b3ef104e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-0.0.14-javadoc.jar",
          "url": "dapanda-api-core-0.0.14-javadoc.jar",
          "size": 255894,
          "sha512": "0e6ceb82531e3e73ba388caa2e117c4d341ffa6605e65baa4cd4f6273f5751e11a53b38c056f2f533dfa2855b42f6d2416e1effdfdc97299e7c73a0cb9e3e0b3",
          "sha256": "196a00086aa5f7429489c3bfc65930c7c41c2d19863d90ab7b618c3c9131ab39",
          "sha1": "5ebbe488b08ac06888a528135ecc1280e17f2bad",
          "md5": "5880497e0e35f2ce27f45ebcdf4fe5f9"
        }
      ]
    }
  ]
}
