{
  "formatVersion": "1.1",
  "component": {
    "group": "dapanda.api.core",
    "module": "dapanda-api-core",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-jackson-databind"
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jackson"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut.platform",
          "module": "micronaut-platform",
          "version": {
            "requires": "4.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-1.0.3.jar",
          "url": "dapanda-api-core-1.0.3.jar",
          "size": 615756,
          "sha512": "a6c32e193eb68683db07ee255f9a1fc3d56005c365c850be07521214b2a654d8b7eb42873fa906df3b1d12dfb768ef67a6489b9f475265801ac6498bee4e75b7",
          "sha256": "8d0d3b6f758b42f4b215eed387a6c032f5014b1dbe2ffc6267aca6f05fba5316",
          "sha1": "b302ff6040acf6ea0b686b2f6b47a2517a0b3f15",
          "md5": "e90d8cf4a44da588b250fcc3fa58c953"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-http-server-netty"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-http-client"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-runtime"
        },
        {
          "group": "io.micronaut.kotlin",
          "module": "micronaut-kotlin-runtime"
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api"
        },
        {
          "group": "io.micronaut.validation",
          "module": "micronaut-validation"
        },
        {
          "group": "jakarta.el",
          "module": "jakarta.el-api",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "io.micronaut.beanvalidation",
          "module": "micronaut-hibernate-validator",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "org.glassfish",
          "module": "jakarta.el",
          "version": {
            "requires": "4.0.2"
          }
        },
        {
          "group": "io.micronaut.sql",
          "module": "micronaut-jdbc-hikari"
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-core"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-caffeine"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-noop"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-slf4j",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "8.0.33"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-jackson-databind"
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jackson"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut.platform",
          "module": "micronaut-platform",
          "version": {
            "requires": "4.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-1.0.3.jar",
          "url": "dapanda-api-core-1.0.3.jar",
          "size": 615756,
          "sha512": "a6c32e193eb68683db07ee255f9a1fc3d56005c365c850be07521214b2a654d8b7eb42873fa906df3b1d12dfb768ef67a6489b9f475265801ac6498bee4e75b7",
          "sha256": "8d0d3b6f758b42f4b215eed387a6c032f5014b1dbe2ffc6267aca6f05fba5316",
          "sha1": "b302ff6040acf6ea0b686b2f6b47a2517a0b3f15",
          "md5": "e90d8cf4a44da588b250fcc3fa58c953"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-1.0.3-sources.jar",
          "url": "dapanda-api-core-1.0.3-sources.jar",
          "size": 207136,
          "sha512": "ec1594bd94fedf6b4c01bb64fe299598028ba62424df1b039446f56326f93057271d8b1d288026d96bf9ee7d5b1482b6e7340f9dc99e38db5bd9da994225d2c3",
          "sha256": "a965b052e85c80029b989c12dc910abfa18a8f306bada8986d5732ec054e9da6",
          "sha1": "2650660d99be3af185f6f36c210a38452e0a2703",
          "md5": "8a10ff7540a765618529aca3c8bc5f5a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-1.0.3-javadoc.jar",
          "url": "dapanda-api-core-1.0.3-javadoc.jar",
          "size": 272041,
          "sha512": "98eba29cd8a3735a9bd2dedebed6307c2b5fc611e2a54a1a5633a5da9899e76d3095c4274d55a4fcf60c9e6a05b740703e9a44862545436a5ede0808b01e22fb",
          "sha256": "d692e17765ab48ea065d6f390856dfdddf9e6576dbaabf8884e7474cdae042c7",
          "sha1": "cd926f8b8ea8d0a3f8c065695ee714918f9cf39f",
          "md5": "36955fa31021c49aff899e6f88bbaa6b"
        }
      ]
    }
  ]
}
