{
  "formatVersion": "1.1",
  "component": {
    "group": "dapanda.api.core",
    "module": "dapanda-api-core",
    "version": "0.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jackson"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.9.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-0.0.19.jar",
          "url": "dapanda-api-core-0.0.19.jar",
          "size": 498386,
          "sha512": "da2fb2d460e31cfcae3556efb400f829ce6af24e3c9f44f8c95b7e01a1f97bea0466bfc46ce181d73dc4149316853e56b8f68fe916330104ef4449c2581f206e",
          "sha256": "dce3268557c56784ad578d525a0ec9ba2924beaf346c91f85f191cfdae9a4b83",
          "sha1": "6b4b47cf56ca57515115ef3163d8c953ef26edf2",
          "md5": "b0f15ee39fa9a2c2a8161cfcc032b5a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-http-server-netty"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-http-client"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-runtime"
        },
        {
          "group": "io.micronaut.kotlin",
          "module": "micronaut-kotlin-runtime"
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-validation"
        },
        {
          "group": "io.micronaut.beanvalidation",
          "module": "micronaut-hibernate-validator"
        },
        {
          "group": "io.micronaut.sql",
          "module": "micronaut-jdbc-hikari"
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-core"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-caffeine"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-noop"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-slf4j",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "8.0.33"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jackson"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.9.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-0.0.19.jar",
          "url": "dapanda-api-core-0.0.19.jar",
          "size": 498386,
          "sha512": "da2fb2d460e31cfcae3556efb400f829ce6af24e3c9f44f8c95b7e01a1f97bea0466bfc46ce181d73dc4149316853e56b8f68fe916330104ef4449c2581f206e",
          "sha256": "dce3268557c56784ad578d525a0ec9ba2924beaf346c91f85f191cfdae9a4b83",
          "sha1": "6b4b47cf56ca57515115ef3163d8c953ef26edf2",
          "md5": "b0f15ee39fa9a2c2a8161cfcc032b5a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-0.0.19-sources.jar",
          "url": "dapanda-api-core-0.0.19-sources.jar",
          "size": 184267,
          "sha512": "91741ab81f0794fb2a4c3800fdbd83b11aae65b32e3a306f0f4526a094ce7757ca2c681839c3779b514515574cd913ade2bc25e76ee831467548a67ca903e7b3",
          "sha256": "130840e37c0280859aa446aae67681122b52492b319db84797c7e31ebc9e765d",
          "sha1": "9520084cc464d1d535c1ee06b9e50b916f905797",
          "md5": "f447454d4e312403ef623b035d3cf1f0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-0.0.19-javadoc.jar",
          "url": "dapanda-api-core-0.0.19-javadoc.jar",
          "size": 255899,
          "sha512": "618957483d672a36576607e11ef3698b8ea5d22da94b6ce8edfdb1dbccdfbaa52cbbbdb0c0f3ea2f07e8f88bf224dec88b132ddf02e601f617676ceeb8e342e6",
          "sha256": "ecb71bcb1ed9c05d9b1641e553c8c208a9bd00416bf10db7ab11bd37b9c6f824",
          "sha1": "bd7c07c80e86c3d82ebef952872bfad23b8e3521",
          "md5": "2c0405a1b93193954fc1ad3225274971"
        }
      ]
    }
  ]
}
