{
  "formatVersion": "1.1",
  "component": {
    "group": "dapanda.api.core",
    "module": "dapanda-api-core",
    "version": "0.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jackson"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.9.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-0.0.18.jar",
          "url": "dapanda-api-core-0.0.18.jar",
          "size": 488848,
          "sha512": "272bb2c1810182c488d526b4804dea43b094b58a974ba73490b466794734db192ad3b37dda98189859079a48b3e89a10e780bddde18d3865aff60e152af8f3ee",
          "sha256": "4f2e37e9e6a85fec0648cfaccf3568003d690d84e8ef4de95b95fbf3e41f6093",
          "sha1": "8420ca14c5c3ae95f5ea61af98c984938561534c",
          "md5": "bc06c0957362de73aa5875b2e6ed6cef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-http-server-netty"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-http-client"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-runtime"
        },
        {
          "group": "io.micronaut.kotlin",
          "module": "micronaut-kotlin-runtime"
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-validation"
        },
        {
          "group": "io.micronaut.beanvalidation",
          "module": "micronaut-hibernate-validator"
        },
        {
          "group": "io.micronaut.sql",
          "module": "micronaut-jdbc-hikari"
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-core"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-caffeine"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-noop"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-slf4j",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "8.0.33"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jackson"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-bom",
          "version": {
            "requires": "3.9.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.7"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-0.0.18.jar",
          "url": "dapanda-api-core-0.0.18.jar",
          "size": 488848,
          "sha512": "272bb2c1810182c488d526b4804dea43b094b58a974ba73490b466794734db192ad3b37dda98189859079a48b3e89a10e780bddde18d3865aff60e152af8f3ee",
          "sha256": "4f2e37e9e6a85fec0648cfaccf3568003d690d84e8ef4de95b95fbf3e41f6093",
          "sha1": "8420ca14c5c3ae95f5ea61af98c984938561534c",
          "md5": "bc06c0957362de73aa5875b2e6ed6cef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-0.0.18-sources.jar",
          "url": "dapanda-api-core-0.0.18-sources.jar",
          "size": 182770,
          "sha512": "ea4f8ffe8c7028e7bf37ffa455a930093d0f4c1a8a1a24fe68db7127b06ac0fa25824704dca24322d56fdaa7c778c16b6a9371b090f5c25736f254b2dfb455e3",
          "sha256": "5c1557884ea30f3c1393a7d9e0e2f092db67f87e522f6361dc8491a11860b71e",
          "sha1": "07532641e1a7254e122d0a740133147d5bb16f71",
          "md5": "9927de39b49372bf2f69d7e5521c30d2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-0.0.18-javadoc.jar",
          "url": "dapanda-api-core-0.0.18-javadoc.jar",
          "size": 255896,
          "sha512": "0d6c22fceea0490898d8968fd0c8f8303c55e6a0edbc8d2b6b822e9f94a3ea2894b8b55f2b9b680545e6917c81e85fe6694e6cfd1f645d51e041341ad26e197b",
          "sha256": "788f3d2e7ae5be7fdb5debca90ef24846b18e0720e3d444b5386e40261579713",
          "sha1": "121284548e67dcee09d85a200b5606591242dbb8",
          "md5": "2ce2da3a30281c8fc25ebbb68d40817f"
        }
      ]
    }
  ]
}
