{
  "formatVersion": "1.1",
  "component": {
    "group": "dapanda.api.core",
    "module": "dapanda-api-core",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-jackson-databind"
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jackson"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut.platform",
          "module": "micronaut-platform",
          "version": {
            "requires": "4.4.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-1.0.4.jar",
          "url": "dapanda-api-core-1.0.4.jar",
          "size": 615578,
          "sha512": "aa48225e039b14e515f0ce8c7056a3871a808f5342fcc055339dcf5c39aafcb2dd7a50b3eee6eab739b631f95cf8fe94b261e4d5064a598d45c460ae62106db9",
          "sha256": "a1ac4f9ab3b31fd6d2e8a8dfa274af5d1aba88f7910f6f7d12665ec81a654a30",
          "sha1": "7d5d2e3a22fcc02f6188a62bdfbaf5d7e22f0aa1",
          "md5": "8fc81971b48f5e28702ed9f1fb180da9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.micronaut",
          "module": "micronaut-http-server-netty"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-http-client"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-runtime"
        },
        {
          "group": "io.micronaut.kotlin",
          "module": "micronaut-kotlin-runtime"
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api"
        },
        {
          "group": "io.micronaut.validation",
          "module": "micronaut-validation"
        },
        {
          "group": "jakarta.el",
          "module": "jakarta.el-api",
          "version": {
            "requires": "6.0.1"
          }
        },
        {
          "group": "io.micronaut.sql",
          "module": "micronaut-jdbc-hikari"
        },
        {
          "group": "io.micronaut.micrometer",
          "module": "micronaut-micrometer-core"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-caffeine"
        },
        {
          "group": "io.micronaut.cache",
          "module": "micronaut-cache-noop"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-slf4j",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j",
          "version": {
            "requires": "8.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names"
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-jackson-databind"
        },
        {
          "group": "io.micronaut.serde",
          "module": "micronaut-serde-jackson"
        },
        {
          "group": "io.micronaut",
          "module": "micronaut-inject"
        },
        {
          "group": "io.micronaut.platform",
          "module": "micronaut-platform",
          "version": {
            "requires": "4.4.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml"
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "dapanda-api-core-1.0.4.jar",
          "url": "dapanda-api-core-1.0.4.jar",
          "size": 615578,
          "sha512": "aa48225e039b14e515f0ce8c7056a3871a808f5342fcc055339dcf5c39aafcb2dd7a50b3eee6eab739b631f95cf8fe94b261e4d5064a598d45c460ae62106db9",
          "sha256": "a1ac4f9ab3b31fd6d2e8a8dfa274af5d1aba88f7910f6f7d12665ec81a654a30",
          "sha1": "7d5d2e3a22fcc02f6188a62bdfbaf5d7e22f0aa1",
          "md5": "8fc81971b48f5e28702ed9f1fb180da9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-1.0.4-sources.jar",
          "url": "dapanda-api-core-1.0.4-sources.jar",
          "size": 207136,
          "sha512": "4e2811a6e8e99821a426601920fed221a56e0cb3bc2ebc5d0edbc0b06528908805eaaa9ddae2e1b6c969c83ab873c0c3a4c1d53237475ad672a7118b5d1c46b9",
          "sha256": "b0455056a753ab4f37d7d12ab80799647dc738c30d53d103d28d8fbdfc942a81",
          "sha1": "a83d75b724313526db05e8522ea499d39cc0be1e",
          "md5": "acf7fde571c1869fc32224fe6f0bdae7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dapanda-api-core-1.0.4-javadoc.jar",
          "url": "dapanda-api-core-1.0.4-javadoc.jar",
          "size": 271996,
          "sha512": "9885aa0bc5dcf722508ddf49be6efe319b7aebb729a53cd1f2d734853db92415b91e2ce5ba48ce28176a64a9f718055d5cea77a1312a2ad565c0cd8e03aee51d",
          "sha256": "cfb6bf536fb991977bb5fdd6798e26338c3389aacb1245918663601b1a7950ae",
          "sha1": "7aa15fed136ca0b8589c4bd2248671c40424c6ff",
          "md5": "5d807d0342635d4fdc409f5763047b7a"
        }
      ]
    }
  ]
}
